mensajeria/applications/servicios/urls.py
from django.urls import path
from .views import( CrearServicioView, VerServiciosCliente, HistorialServiciosClienteView, 
                   ServiciosDisponiblesParaMensajeroView, AceptarServicioView, GestionarServicioView, 
                   CompletarServicioView, HistorialServiciosMensajeroView, ServicioListView, generarReporte)

app_name = "servicios_app"

urlpatterns = [
    path('crear-servicio/', CrearServicioView.as_view(), name='crear_servicio'),
    path('listar-servicio/', VerServiciosCliente.as_view(), name='listar_servicio'),
    path('historialCliente/', HistorialServiciosClienteView.as_view(), name='historialCliente'),
    path('seleccionarServicio/', ServiciosDisponiblesParaMensajeroView.as_view(), name = 'listar_servicios_mensajero'),
    path('aceptar-servicio/<int:servicio_id>/', AceptarServicioView.as_view(), name='aceptar_servicio'),
    path('gestionar-servicio/', GestionarServicioView.as_view(), name = 'gestionarServicio'),
    path('servicio/completar/', CompletarServicioView.as_view(), name='completarServicio'),
    path('historialMensajero/', HistorialServiciosMensajeroView.as_view(), name='historialMensajero'),
    path('listarServiciosAdmin/', ServicioListView.as_view(), name='admin_servicio_list'),
    
    path('reporte/<int:usuario_id>/', generarReporte, name='generarReporte'),
]

mensajeria/mensajeria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.users.urls')),
    path('', include('applications.servicios.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mensajeria/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mi Sitio Web{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/stylesBase.css' %}">
    <link rel="stylesheet" href="{% static 'css/stylesForm.css' %}">
    
    {% block extra_css %}
    <!-- CSS adicional puede ser añadido aquí desde las plantillas hijas -->
    {% endblock %}
</head>
<body>
    <header>
        <nav>
            <div class="logo">Mensajería BBC</div>
                <div class="nav-links">
                    <a href="#about">Acerca de Nosotros</a>
                    <a href="#services">Servicios</a>
                    <a href="#testimonials">Testimonios</a>
                    <a href="#contact">Contacto</a>
                    {% if user.is_authenticated and user.is_mensajero %}
                        <a href="{% url 'servicios_app:gestionarServicio' %}">Gestionar Servicio</a>
                        <a href="{% url 'servicios_app:listar_servicios_mensajero' %}">Aceptar Servicio</a>
                        <a href="{% url 'servicios_app:historialMensajero' %}">Historial de Servicios</a>
                        <a href="{% url 'updateUser' user.id%}">Actualizar Perfil</a>
                        <a href="{% url 'logout' %}">Logout</a>
                        <div class="profile">
                            {% if user.imagenPerfil %}
                            <img src="{{ user.imagenPerfil.url }}" alt="Imagen de Perfil" class="profile-img" id="profile-img">
                            {% else %}
                            <img src="{% static 'images/defecto.png' %}" alt="Imagen de Perfil" class="profile-img" id="profile-img">
                            {% endif %}
                            
                        </div>
                    {% elif user.is_authenticated and user.is_cliente %}
                        <a href="{% url 'servicios_app:crear_servicio' %}">Solicitar servicio</a>
                        <a href="{% url 'servicios_app:listar_servicio' %}">Estado de servicio</a>
                        <a href="{% url 'servicios_app:historialCliente' %}">Historial de Servicios</a>
                       
                        <a href="{% url 'updateUser' user.id%}">Actualizar Perfil</a>
                        <a href="{% url 'logout' %}">Logout</a>
                        <div class="profile">
                            {% if user.imagenPerfil %}
                                <img src="{{ user.imagenPerfil.url }}" alt="Profile Image" class="profile-img">
                            {% else %}
                                <img src="{% static 'images/defecto.png' %}" alt="Profile Image" class="profile-img">
                            {% endif %}
                        </div>
                    {% elif user.is_authenticated and user.is_staff %}
                    <a href="{% url 'list_user' %}">Ver Usuarios</a>
                    <a href="{% url 'servicios_app:admin_servicio_list' %}">Ver domicilios</a>
                    <a href="{% url 'updateUser' user.id%}">Actualizar Perfil</a>
                    <a href="{% url 'logout' %}">Logout</a>
                    <a href="#historial-servicios">Generar informe</a>
                    <div class="profile">
                        {% if user.imagenPerfil %}
                            <img src="{{ user.imagenPerfil.url }}" alt="Profile Image" class="profile-img">
                        {% else %}
                            <img src="{% static 'images/defecto.png' %}" alt="Profile Image" class="profile-img">
                        {% endif %}
                    </div>


                    {% else %}
                        <a href="{% url 'create_cliente' %}">Registrate</a>
                        <a href="{% url 'create_mensajero' %}">¡Trabaja con nosotros!</a>
                        <a href="{% url 'login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </nav>
        <h1>Envíos rápidos y seguros a cualquier destino</h1>
    </header>

    <main>
        {% block content %}
        <!-- El contenido principal va aquí -->
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2024 Mensajería Express. Todos los derechos reservados.</p>
    </footer>

    {% block extra_js %}
    <!-- JavaScript adicional puede ser añadido aquí desde las plantillas hijas -->
    {% endblock %}


    
</body>
</html>