mensajeria/applications/servicios/urls.py
from django.urls import path
from .views import( CrearServicioView, VerServiciosCliente, HistorialServiciosClienteView, 
                   ServiciosDisponiblesParaMensajeroView, AceptarServicioView, GestionarServicioView, 
                   CompletarServicioView, HistorialServiciosMensajeroView, ServicioListView, generarReporte)

app_name = "servicios_app"

urlpatterns = [
    path('crear-servicio/', CrearServicioView.as_view(), name='crear_servicio'),
    path('listar-servicio/', VerServiciosCliente.as_view(), name='listar_servicio'),
    path('historialCliente/', HistorialServiciosClienteView.as_view(), name='historialCliente'),
    path('seleccionarServicio/', ServiciosDisponiblesParaMensajeroView.as_view(), name = 'listar_servicios_mensajero'),
    path('aceptar-servicio/<int:servicio_id>/', AceptarServicioView.as_view(), name='aceptar_servicio'),
    path('gestionar-servicio/', GestionarServicioView.as_view(), name = 'gestionarServicio'),
    path('servicio/completar/', CompletarServicioView.as_view(), name='completarServicio'),
    path('historialMensajero/', HistorialServiciosMensajeroView.as_view(), name='historialMensajero'),
    path('listarServiciosAdmin/', ServicioListView.as_view(), name='admin_servicio_list'),
    
    path('reporte/<int:usuario_id>/', generarReporte, name='generarReporte'),
]

mensajeria/mensajeria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.users.urls')),
    path('', include('applications.servicios.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mensajeria/applications/servicios/models.py
from django.db import models
from django.conf import settings
import requests
from django.core.exceptions import ValidationError
from applications.users.models import CustomUser
from .managers import ManajerServicios

# Create your models here.

class Direccion(models.Model):
    direccion = models.CharField(max_length=300)
    CIUDAD_CHOICES = (
        ('C','Santiago de Cali'),
        ('B','Bogota'),
        ('M','Medellin'),
        ('P','Pereira'),
    )
    ciudad = models.CharField(max_length=100, choices=CIUDAD_CHOICES)
    departamento = models.CharField(max_length=100)
    codigo_postal = models.CharField(max_length=20)
    pais = models.CharField(max_length=100)
    latitud = models.FloatField(null=True, blank=True)
    longitud = models.FloatField(null=True, blank=True)

    class Meta:
        verbose_name = 'Dirección'
        verbose_name_plural = 'Direcciones'

    def __str__(self):
        return f'{self.direccion}, {self.ciudad}, {self.departamento}, {self.pais}, {self.codigo_postal}'

    def get_lat_long_google(address, city, country, department, api_key):
        full_address = f"{address}, {city}, {department}, {country}"
        geocoding_url = f"https://maps.googleapis.com/maps/api/geocode/json?address={full_address}&key={api_key}"
        
        # Imprimir la URL para depuración
        print(f"URL de geocodificación: {geocoding_url}")
        
        response = requests.get(geocoding_url)
        
        if response.status_code == 200:
            data = response.json()
            
            # Imprimir la respuesta JSON para depuración
            print(f"Respuesta JSON: {data}")
            
            if data['results']:
                location = data['results'][0]['geometry']['location']
                return location['lat'], location['lng']
        else:
            print(f"Error: {response.status_code}")
            print(response.text)
        
        return None, None

    def save(self, *args, **kwargs):
        if not self.latitud or not self.longitud:
            address = f'{self.direccion}, {self.get_ciudad_display()}, {self.departamento}, {self.pais}'
            api_key = 'AIzaSyDIsLYWRxE2ME1PBLk1ugSZvu8OLfoAuKE'
            geocoding_url = f'https://maps.googleapis.com/maps/api/geocode/json?address={address}&key={api_key}'
            
            # Realiza la solicitud a la API de Google Maps
            response = requests.get(geocoding_url)
            if response.status_code == 200:
                result = response.json()
                if result['status'] == 'OK':
                    self.latitud = result['results'][0]['geometry']['location']['lat']
                    self.longitud = result['results'][0]['geometry']['location']['lng']
            else:
                raise ValidationError('Error al contactar con la API de Google Maps.')

        # Llama al método save original para guardar el objeto
        super().save(*args, **kwargs)

class Servicio(models.Model):
    id_cliente = models.ForeignKey(CustomUser, 
                                   on_delete=models.CASCADE, 
                                   related_name='servicios_cliente', 
                                   blank=False, 
                                   null=False)
    id_mensajero = models.ForeignKey(CustomUser, 
                                     on_delete=models.CASCADE, 
                                     related_name='servicios_mensajero', 
                                     blank=True, 
                                     null=True)
    
    VEHICULO_CHICES = (
        ('M','Moto'),
        ('C','Carro'),
        ('F','Camion'),
    )

    cantidadPaquetes = models.BigIntegerField(blank = True, null = True)

    vehiculoSolicitado = models.CharField(max_length=1 , choices = VEHICULO_CHICES, blank = True)
    direccion_recojer = models.ForeignKey(Direccion, on_delete = models.CASCADE, related_name = 'direccion1', blank = False, null = False)
    direccion_destino = models.ForeignKey(Direccion, on_delete = models.CASCADE, related_name = 'direccion2', blank = False, null = False)
    SERVICIO_ESTADOS = (
        ('S', 'Solicitado.'),
        ('A', 'Agendado, un mensajero tomo tu pedido.'),
        ('C', 'Tu envío está en camino.'),
        ('D', 'Tu envío ha llegado a su destino.'),
        ('E', 'Tu envío ha sido entregado.'),
    )
    estados = models.CharField(max_length=1, choices=SERVICIO_ESTADOS, blank=True)

    def getEstado(self):
        return self.get_estados_display()


    descripcion = models.CharField(max_length=300, null=False, blank=False)
    is_complete = models.BooleanField(blank = True, null = True, default = False)
    fecha_creacion = models.DateTimeField(auto_now_add=True)


    objects = models.Manager()  
    servicios_cliente = ManajerServicios()  


    class Meta:
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios'

    def __str__(self):  
        return f'Servicio {self.id} - {self.descripcion}'

mensajeria/applications/servicios/forms.py
from django import forms
from .models import Direccion, Servicio
from applications.users.models import CustomUser

class DireccionForm(forms.ModelForm):
    class Meta:
        model = Direccion
        fields = ['direccion', 'ciudad', 'departamento', 'codigo_postal', 'pais']
        widgets = {
            'direccion': forms.TextInput(attrs={'class': 'form-control'}),
            'ciudad': forms.Select(attrs={'class': 'form-control'}),
            'departamento': forms.TextInput(attrs={'class': 'form-control'}),
            'codigo_postal': forms.TextInput(attrs={'class': 'form-control'}),
            'pais': forms.TextInput(attrs={'class': 'form-control'}),   
        }

class ServicioForm(forms.ModelForm):
    class Meta:
        model = Servicio
        fields = ['descripcion', 'vehiculoSolicitado']
        widgets = {
            'descripcion': forms.TextInput(attrs={'class': 'form-control'}),
            'vehiculoSolicitado': forms.Select(attrs={'class': 'form-control'}),   
        }

class ServicioEstadoForm(forms.ModelForm):
    class Meta:
        model = Servicio
        fields = ['estados']
        widgets = {
            'estados': forms.Select(attrs={'class': 'form-control'}), 
        }

    def save(self, commit=True):
        servicio = super().save(commit=False)
        
        #if self.cleaned_data.get('imagenEstado'):
        #    servicio.imagenEstado = self.cleaned_data['imagenEstado']
        #else:
        #    if self.instance.pk:
        #        previous_instance = Servicio.objects.get(pk=self.instance.pk)
        #        servicio.imagenEstado = previous_instance.imagenEstado
        
        #if commit:
        #    servicio.save()
        servicio.save()
        
        return servicio
    

class ServicioFilterForm(forms.Form):
    CIUDAD_CHOICES = (
        ('', 'Todas...'),
        ('C','Santiago de Cali'),
        ('B','Bogota'),
        ('M','Medellin'),
        ('P','Pereira'),
    )

    is_complete = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    ciudad_ida = forms.ChoiceField(choices=CIUDAD_CHOICES, required=False)
    ciudad_llegada = forms.ChoiceField(choices=CIUDAD_CHOICES, required=False)
    fecha_creacion = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}))

mensajeria/applications/servicios/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView
from django.shortcuts import render, redirect
from django.forms import modelformset_factory
from .models import Direccion, Servicio
from applications.users.models import CustomUser
from .forms import DireccionForm, ServicioForm, ServicioEstadoForm, ServicioFilterForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect, get_object_or_404
from django.utils.timezone import make_aware
from datetime import datetime
from django.http import HttpResponse
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from datetime import datetime
from django.urls import reverse_lazy


class CrearServicioView(View, LoginRequiredMixin):

    def get(self, request, *args, **kwargs):
        direccion_formset = modelformset_factory(Direccion, form=DireccionForm, extra=2)
        formset = direccion_formset(queryset=Direccion.objects.none())
        servicio_form = ServicioForm()
        return render(request, 'servicios/crearServicio.html', {'formset': formset, 'servicio_form': servicio_form})

    def post(self, request, *args, **kwargs):
        direccion_formset = modelformset_factory(Direccion, form=DireccionForm, extra=2)
        formset = direccion_formset(request.POST)
        servicio_form = ServicioForm(request.POST)

        if formset.is_valid() and servicio_form.is_valid():
            direcciones = formset.save()
            servicio = servicio_form.save(commit=False)
            servicio.direccion_recojer = direcciones[0]
            servicio.direccion_destino = direcciones[1]
            servicio.estados = 'S'
            servicio.id_cliente = request.user 
            servicio.id_mensajero = None 
            servicio.is_complete = False
            servicio.save()
            return redirect('indexCliente')

        return render(request, 'servicios/crearServicio.html', {'formset': formset, 'servicio_form': servicio_form})


class ClienteRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_cliente

class MensajeroRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_mensajero    


class VerServiciosCliente(TemplateView):
    template_name = "servicios/serviciosEstado.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        servicios = Servicio.servicios_cliente.get_servicios_cliente(self.request.user)
        print(servicios)
        context['servicios'] = servicios
        return context
    

class ServiciosDisponiblesParaMensajeroView(MensajeroRequiredMixin, ListView):
    template_name = "servicios/serviciosMensajero.html"
    context_object_name = 'servicios'

    def get_queryset(self):
        usuario = self.request.user
        if usuario.is_mensajero and not Servicio.servicios_cliente.tieneServicio(usuario):
            return Servicio.servicios_cliente.get_servicios_disponibles_para_mensajero(usuario)
        return Servicio.objects.none()
    

class AceptarServicioView(MensajeroRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        servicio_id = kwargs.get('servicio_id')
        servicio = get_object_or_404(Servicio, id=servicio_id)
        
        if servicio.id_mensajero is None:
            servicio.id_mensajero = request.user
            servicio.estados = 'A'  # Cambiar el estado del servicio si es necesario
            servicio.save()
            return redirect('indexMensajero')
        else:
            return redirect('ver_servicios_disponibles')  # O algún mensaje de error



class GestionarServicioView(MensajeroRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        servicio = Servicio.servicios_cliente.get_servicio_actual(request.user)
        if not servicio:
            return render(request, 'users/indexMensajero.html')  
        form = ServicioEstadoForm(instance=servicio)
        return render(request, 'servicios/gestionarServicioMensajero.html', {'form': form, 'servicio': servicio})
    
    def post(self, request, *args, **kwargs):
        servicio = Servicio.servicios_cliente.get_servicio_actual(request.user)
        if not servicio:
            return render(request, 'users/indexMensajero.html')  

        form = ServicioEstadoForm(request.POST, request.FILES, instance=servicio)
        if form.is_valid():
            form.save()
            return redirect('servicios_app:gestionarServicio')

        return render(request, 'servicios/gestionarServicioMensajero.html', {'form': form, 'servicio': servicio})
    


class CompletarServicioView(MensajeroRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        servicio = Servicio.servicios_cliente.get_servicio_actual(request.user)
        if not servicio:
            return render(request, 'servicios/no_servicio.html')  

        servicio.is_complete = True
        servicio.estados = 'E'
        servicio.save()

        return redirect('indexMensajero')
    


class HistorialServiciosMensajeroView(TemplateView, MensajeroRequiredMixin):
    template_name = "servicios/historialMensajero.html"

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        historial = Servicio.servicios_cliente.get_historial_servicios_mensajeros(self.request.user)
        print(historial)
        context['historial'] = historial
        return context
    

class HistorialServiciosClienteView(TemplateView, ClienteRequiredMixin):
    template_name = "servicios/historialCliente.html"

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        historial = Servicio.servicios_cliente.get_historial_servicios_cliente(self.request.user)
        print(historial)
        context['historial'] = historial
        return context



class ServicioListView(ListView):
    model = Servicio
    template_name = "Admin/listarServiciosAdmin.html"
    context_object_name = 'servicios'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        form = ServicioFilterForm(self.request.GET)
        if form.is_valid():

            ciudad_ida = form.cleaned_data.get('ciudad_ida')
            if ciudad_ida:
                queryset = queryset.filter(direccion_recojer__ciudad=ciudad_ida)
                print(ciudad_ida)
                print(queryset)

            ciudad_llegada = self.request.GET.get('ciudad_llegada')
            if ciudad_llegada:
                queryset = queryset.filter(direccion_destino__ciudad=ciudad_llegada)
                

            is_complete = self.request.GET.get('is_complete')
            if is_complete:
                queryset = queryset.filter(is_complete = True)

            fecha_creacion = self.request.GET.get('fecha_creacion')
            if fecha_creacion:
                print(fecha_creacion)
                fecha_creacion = make_aware(datetime.strptime(fecha_creacion, '%Y-%m-%d'))
                queryset = queryset.filter(fecha_creacion__gte = fecha_creacion)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ServicioFilterForm(self.request.GET or None)  
        return context
    


def generarReporte(request, usuario_id):
    usuario = get_object_or_404(CustomUser, id=usuario_id)
    if usuario.is_mensajero:
        servicios = Servicio.objects.filter(id_mensajero=usuario)
    else:
        servicios = Servicio.objects.filter(id_cliente=usuario)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="reporte_{usuario.username}.pdf"'

    p = canvas.Canvas(response, pagesize=letter)
    width, height = letter

    
    p.setFont("Helvetica-Bold", 16)
    p.drawString(30, height - 30, f"Reporte de Envíos para {usuario.username}")

    p.setFont("Helvetica", 12)
    p.drawString(30, height - 60, f"Fecha: {datetime.now().strftime('%Y-%m-%d')}")

    
    p.setFont("Helvetica-Bold", 14)
    p.drawString(30, height - 90, "Servicios asociados:")

    y = height - 110
    for servicio in servicios:
        p.setFont("Helvetica", 12)
        p.drawString(30, y, f"ID: {servicio.id}, Descripción: {servicio.descripcion}, Estado: {servicio.getEstado()}, Fecha: {servicio.fecha_creacion.strftime('%Y-%m-%d')}")
        y -= 20
        if y < 50:  
            p.showPage()
            y = height - 50

    p.showPage()
    p.save()

    return response

mensajeria/templates/servicios/crearServicio.html
{% extends 'base.html' %}

{% block title %}Crear Servicio{% endblock %}

{% block content %}
<div class="form-container">
    <h1>Solicitar servicio</h1> <!-- Se ajustó el margen inferior a mb-2 -->
    <form method="post">
        {% csrf_token %}
        {{ formset.management_form }}

        <!-- Sección para Crear Servicio -->
        <div class="form-section">
            <h3>Crear Servicio</h3>
            <div class="form-group">
                {{ servicio_form.descripcion.label_tag }}
                {{ servicio_form.descripcion }}
                {% if servicio_form.errors.descripcion %}
                <div class="error-message">{{ servicio_form.errors.descripcion }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ servicio_form.vehiculoSolicitado.label_tag }}
                {{ servicio_form.vehiculoSolicitado }}
                {% if servicio_form.errors.vehiculoSolicitado %}
                <div class="error-message">{{ servicio_form.errors.vehiculoSolicitado }}</div>
                {% endif %}
            </div>
        </div>

        <!-- Sección para Dirección de Recogida -->
        <div class="form-section">
            <h3>Dirección de Recogida</h3>
            <div class="form-group">
                {{ formset.forms.0.direccion.label_tag }}
                {{ formset.forms.0.direccion }}
                {% if formset.forms.0.errors.direccion %}
                <div class="error-message">{{ formset.forms.0.errors.direccion }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ formset.forms.0.ciudad.label_tag }}
                {{ formset.forms.0.ciudad }}
                {% if formset.forms.0.errors.ciudad %}
                <div class="error-message">{{ formset.forms.0.errors.ciudad }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ formset.forms.0.departamento.label_tag }}
                {{ formset.forms.0.departamento }}
                {% if formset.forms.0.errors.departamento %}
                <div class="error-message">{{ formset.forms.0.errors.departamento }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ formset.forms.0.codigo_postal.label_tag }}
                {{ formset.forms.0.codigo_postal }}
                {% if formset.forms.0.errors.codigo_postal %}
                <div class="error-message">{{ formset.forms.0.errors.codigo_postal }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ formset.forms.0.pais.label_tag }}
                {{ formset.forms.0.pais }}
                {% if formset.forms.0.errors.pais %}
                <div class="error-message">{{ formset.forms.0.errors.pais }}</div>
                {% endif %}
            </div>
        </div>

        <!-- Sección para Dirección de Destino -->
        <div class="form-section">
            <h3>Dirección de Destino</h3>
            <div class="form-group">
                {{ formset.forms.1.direccion.label_tag }}
                {{ formset.forms.1.direccion }}
                {% if formset.forms.1.errors.direccion %}
                <div class="error-message">{{ formset.forms.1.errors.direccion }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ formset.forms.1.ciudad.label_tag }}
                {{ formset.forms.1.ciudad }}
                {% if formset.forms.1.errors.ciudad %}
                <div class="error-message">{{ formset.forms.1.errors.ciudad }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ formset.forms.1.departamento.label_tag }}
                {{ formset.forms.1.departamento }}
                {% if formset.forms.1.errors.departamento %}
                <div class="error-message">{{ formset.forms.1.errors.departamento }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ formset.forms.1.codigo_postal.label_tag }}
                {{ formset.forms.1.codigo_postal }}
                {% if formset.forms.1.errors.codigo_postal %}
                <div class="error-message">{{ formset.forms.1.errors.codigo_postal }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ formset.forms.1.pais.label_tag }}
                {{ formset.forms.1.pais }}
                {% if formset.forms.1.errors.pais %}
                <div class="error-message">{{ formset.forms.1.errors.pais }}</div>
                {% endif %}
            </div>
        </div>
        <br>
        <button type="submit" class="mt-3">Guardar</button> <!-- Se ajustó el margen superior a mt-3 -->
    </form>
</div>
{% endblock %}

mensajeria/templates/servicios/gestionarServicioMensajero.html
{% extends 'base.html' %}

{% block title %}Crear Cliente{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="card">
            <div class="card-header">
                <h2>Gestionar Servicio {{ servicio.id }}</h2>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary" style="width: 160px;">Actualizar Estado</button>
                </form>
                <hr>
                <form method="post" action="{% url 'servicios_app:completarServicio' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success mt-3">Completar Servicio</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

mensajeria/templates/servicios/historialCliente.html
{% extends 'base.html' %}

{% block title %}Historial de Servicios{% endblock %}

{% block content %}
    <div class="form-container">
        <div class="container mt-5">
            <h2>Historial de Servicios</h2>
            <table class="table table-hover mt-4">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Descripción</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Fecha</th>
                        <th scope="col">Dirección de Recogida</th>
                        <th scope="col">Dirección de Entrega</th>
                    </tr>
                </thead>
                <tbody>
                    {% for servicio in historial %}
                    <tr>
                        <th scope="row">{{ servicio.id }}</th>
                        <td>{{ servicio.descripcion }}</td>
                        <td>{{ servicio.get_estados_display }}</td>
                        <td>{{ servicio.fecha_creacion }}</td>
                        <td>{{ servicio.direccion_recojer }}</td>
                        <td>{{ servicio.direccion_destino }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

mensajeria/templates/servicios/historialMensajero.html
{% extends 'base.html' %}

{% block title %}Crear Cliente{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2>Historial de Servicios</h2>
        <table class="table table-hover mt-4">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Descripción</th>
                    <th scope="col">Estado</th>
                    <th scope="col">Fecha</th>
                    <th scope="col">Dirección de Recogida</th>
                    <th scope="col">Dirección de Entrega</th>
                </tr>
            </thead>
            <tbody>
                {% for servicio in historial %}
                <tr>
                    <th scope="row">{{ servicio.id }}</th>
                    <td>{{ servicio.descripcion }}</td>
                    <td>{{ servicio.get_estados_display }}</td>
                    <td>{{ servicio.fecha_creacion }}</td>
                    <td>{{ servicio.direccion_recojer }}</td>
                    <td>{{ servicio.direccion_destino }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

mensajeria/templates/servicios/serviciosEstado.html
{% extends 'base.html' %}

{% block title %}Estado de servicio{% endblock %}

{% block content %}
    <div class="form-container">
        <h2>Estados de los servicios</h2>
        <div class="container">
            <table class="table">
                <thead>
                    <tr>
                        <th>Estado del Servicio</th>
                        <th>Descripción</th>
                        <th>Vehículo Solicitado</th>
                        <th>Mensajero</th>
                    </tr>
                </thead>
                <tbody>
                    {% for servicio in servicios %}
                    <tr>
                        <td>{{ servicio.get_estados_display }}</td>
                        <td>{{ servicio.descripcion }}</td>
                        <td>{{ servicio.get_vehiculoSolicitado_display }}</td>
                        {% if servicio.id_mensajero %}
                            <td>{{ servicio.id_mensajero.username }}</td>
                        {% else %}
                            <td>sin asignacion</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

mensajeria/templates/servicios/serviciosMensajero.html
{% extends 'base.html' %}

{% block title %}Aceptar Servicio{% endblock %}

{% block content %}
    <div class="form-container">
        <h2>Servicios Disponibles</h2>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Descripción</th>
                    <th>Vehículo Solicitado</th>
                    <th>Dirección de Recogida</th>
                    <th>Dirección de Destino</th>
                    <th>Estado</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for servicio in servicios %}
                    <tr>
                        <td>{{ servicio.id }}</td>
                        <td>{{ servicio.descripcion }}</td>
                        <td>{{ servicio.get_vehiculoSolicitado_display }}</td>
                        <td>{{ servicio.direccion_recojer.direccion }}</td>
                        <td>{{ servicio.direccion_destino.direccion }}</td>
                        <td>{{ servicio.get_estados_display }}</td>
                        <td>
                            <form method="post" action="{% url 'servicios_app:aceptar_servicio' servicio.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success">Aceptar</button>
                            </form>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="7" class="text-center">No hay servicios disponibles</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}